version: '3'

services:
  db:
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5
    restart: always
    hostname: db-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    ports:
      - '13306:3306'
