version: '3'

services:
  db:
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    image: mysql:5
    restart: always
    hostname: db-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    ports:
      - '13306:3306'
