version: '3.7'

services:
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: ./dockerfile/api/Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    container_name: db_container
    image: mysql:5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
