version: '3'

services:
  db:
    container_name: db
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

  api:
    container_name: 'api'
    volumes:
      - '~/dev/workspace:/workspace/'
      - 'node_modules_volume:/node_modules'
    build:
      context: ./api/
    ports:
      - '3333:3333'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  client:
    container_name: 'client'
    volumes:
      - '~/dev/workspace:/workspace/'
      - 'node_modules_volume:/node_modules'
    build:
      context: ./client/
    tty: true
    stdin_open: true
    ports:
      - '4200:4200'

  client-manager:
    container_name: 'client-manager'
    volumes:
      - '~/dev/workspace:/workspace/'
      - 'node_modules_volume:/node_modules'
    build:
      context: ./client-manager/
    tty: true
    stdin_open: true
    ports:
      - '4201:4200'

volumes:
  node_modules_volume:
